"""Added company

Revision ID: 4bac05cc7bea
Revises: 5ffa4c2aa8cd
Create Date: 2023-10-10 16:57:58.318091

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bac05cc7bea'
down_revision: Union[str, None] = '5ffa4c2aa8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), server_default=sa.text("'{mylink}'"), nullable=True),
    sa.Column('avatar', sa.String(), server_default=sa.text("'myavatar'"), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('TRUE'), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

