"""Updated Company User

Revision ID: d46990a4a362
Revises: 50fc8eeacdc6
Create Date: 2023-10-15 13:44:35.757331

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46990a4a362'
down_revision: Union[str, None] = '50fc8eeacdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_actions_action_id'), 'actions', ['action_id'], unique=False)
    op.add_column('companies', sa.Column('member_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'member_ids')
    op.drop_index(op.f('ix_actions_action_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###

