version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - app/.env
    ports:
      - 80:80

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=mydb"
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
  tests:
    build:
      context: .
      dockerfile: Dockerfile_test
    command: pytest tests/test_main.py
    env_file:
      - app/.env

volumes:
  postgres_data:
  cache: