FROM python:3.11-slim

WORKDIR /code

COPY ./requirements_dev.txt ./requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r ./requirements_dev.txt

COPY . /code/

ENV PYTHONPATH="$PYTHONPATH:/code/app"

CMD ["pytest", "tests/"]