FROM python:3.11-slim

WORKDIR /code

COPY ./requirements.txt ./requirements.txt

COPY ./requirements_dev.txt ./requirements_dev.txt

RUN pip install --no-cache-dir --upgrade -r ./requirements_dev.txt

COPY . /code/

ENV PYTHONPATH="$PYTHONPATH:/code/app"

CMD ["pytest", "tests/"]