version: '3.8'

services:
  web:
    build: .
    command: python app/main.py
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    env_file:
      - app/.env
    ports:
      - 80:80
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001

volumes:
  postgres_data:
  cache: